### PR TITLE
Create upload endpoint

### PR DESCRIPTION
**Pull request by WillCWX**
# Pull Request

## Description

Creates an upload endpoint with (uploadthing)[https://uploadthing.com/] for profile pictures

Adds `uploadFiles` utility that `ProfileEditor` uses during `handleSubmit` to update profile details.

Notes:
- `uploadthings` added as a dependency, `yarn install` required
- No authentication, will add in after integration
- File verification done by `uploadthing`, might be sufficient

## Screenshots (if applicable)

image
image

## Checklist

- [X] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [X] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [X] I will take care of the merging and delete the side-branch after the PR is merged.

### CODE REVIEW

**Comment by tryyang2001** [comment]
I have tested the upload image function, and it is working. However, I think you need to wait until @hhchinh2002 completed his user service integration, and you also want to polish the upload modal, can consider using the `FileUpload` component that I created, and also set and check the expected file types, and ensure the file image is less than, said 5MB.

**Comment by tryyang2001** [comment]
And another thing is the current branch is actually not working due to merge conflict and the database schema structure is accidentally changed by someone... Hence when you debug, please only run the user service and frontend. I will fix the problems when the user service integration is done.

**Comment by tryyang2001** [comment]
Tested uploading a profile pic, the upload is functioning correctly, but perhaps you forgot to update the SideBar to also include the new avatar update.

**Comment by hhchinh2002** [comment]
> Tested uploading a profile pic, the upload is functioning correctly, but perhaps you forgot to update the SideBar to also include the new avatar update.

actually yall can merge this first and I'll update the sidebar to update user new avatar later in my PR

**Comment by tryyang2001** [comment]
> actually yall can merge this first and I'll update the sidebar to update user new avatar later in my PR

Ermm sure, @WillCWX can you pull from master and resolve the merge conflicts before merging the PR :)

**Comment by WillCWX** [comment]
> > actually yall can merge this first and I'll update the sidebar to update user new avatar later in my PR
> 
> Ermm sure, @WillCWX can you pull from master and resolve the merge conflicts before merging the PR :)

done, need approval, thanks

**Review by tryyang2001 — APPROVED** [review]

**Pull request merged**
