### PR TITLE
Add middleware for frontend to redirect user accessing certain authentication-required pages

### PR DESCRIPTION
**Pull request by hhchinh2002**
# Pull Request

## Description

This PR suppose to:
- Add middleware for frontend to redirect user accessing certain authentication-required pages
- Fix that user context was not set correctly in the last PR #34 
- Add middleware/auth.ts to some user-service router api verify user token

## Related Issue(s)

#34 

## Checklist

- [ ] I have checked that the changes included in the PR are intended to merge to `master` or any destination branch.
- [ ] I have verified that the new changes do not break any existing functionalities, unless the new changes are intended and have approved by the team.
- [ ] I will take care of the merging and delete the side-branch after the PR is merged.

### CODE REVIEW

**Comment by hhchinh2002** [comment]
@tryyang2001 I have to rename middleware.ts export function from `middleware` to `Middleware` cause using `useUserContext` keep giving me this building error:
image
This is also the reason why in the last PR #34 I name it `UseUserContext` which violates our camel naming standard. If you have any workaround then tell me unless we keep this `Middleware` naming

**Comment by tryyang2001** [comment]
Ermm that's why I recommend checking the existence of user cookie for middleware and not the user context, reason being that middleware is running on server side, not client side.

**Comment by hhchinh2002** [comment]
> Ermm that's why I recommend checking the existence of user cookie for middleware and not the user context, reason being that middleware is running on server side, not client side.

Then isn't that the user can just create a `token` field in their cookies with random value and still passed the frontend middleware? Or we jsut let them access the page but when they need to call backend service in those page component, the service will verify the token themselves?

**Comment by hhchinh2002** [comment]
> Ok my bad didn't think carefully. We should do the redirection in individual page that needs authentication access instead of having a centralized control in middleware. Let's not implement token validation in backend for now, we dun have enough time.

it's okay, actually token validation has been implemented already in the first PR #9

**Comment by hhchinh2002** [comment]
Closing this since we're not having middleware.ts in frontend anymore

**Pull request closed without merging**
